[platformio]
default_envs = sender

[env]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  plerup/EspSoftwareSerial@^8.2.0
  file://lib/RadioLibTrim

lib_ignore =
  RadioLib

[env:sender]
build_src_filter =
  -<*>
  +<sender.cpp>
  +<SendOwnInfo.cpp>
  +<U-blox-helper.cpp>
  +<AXP2101.cpp>
upload_port = COM4

[env:receiver]
build_src_filter =
  -<*>
  +<receive.cpp>
upload_port = COM35
[env:pingpong]
build_src_filter =
  -<*>
  +<main.cpp>
  +<SendOwnInfo.cpp>
  +<U-blox-helper.cpp>
  +<AXP2101.cpp>
;upload_port = COM4